
api_version = "2025-07"

[[extensions]]
type = "ui_extension"
name = "redeem"
uid = "c3c10b78-2e00-0902-1bdf-0cd284d1c463b2117697"
handle = "redeem"
description = "A typescript-react POS UI extension"

# module: file that contains your extension’s source code
# target: location where your extension appears in POS
[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
