# POS UI Extension-only app configuration

client_id = "3e0a90c9ecdf9a085dfc7bd1c1c5fa6e"
name = "CreditNote"
application_url = "https://creditnote.vercel.app"
embedded = false
handle = "creditnote"

[build]
automatically_update_urls_on_dev = false

[access_scopes]
scopes = "read_customers,write_customers"
use_legacy_install_flow = false

[pos]
embedded = true
