# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3e0a90c9ecdf9a085dfc7bd1c1c5fa6e"
name = "CreditNote"
application_url = "https://creditnote-41ur.vercel.app"
embedded = true
handle = "creditnote"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "https://creditnote-41ur.vercel.app/api/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://creditnote-41ur.vercel.app/api/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://creditnote-41ur.vercel.app/api/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "customers/create",
  "customers/update",
  "orders/create",
  "orders/updated"
]
  uri = "https://creditnote-41ur.vercel.app/api/webhooks"

[access_scopes]
scopes = "read_customers,read_discounts,read_orders,write_customers,write_discounts,write_orders,read_products,write_products,read_inventory,unauthenticated_read_product_listings,unauthenticated_write_checkouts,unauthenticated_read_checkouts,read_locations,write_draft_orders,read_draft_orders"
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://creditnote-41ur.vercel.app/auth/callback", "https://creditnote-41ur.vercel.app/auth/shopify/callback", "https://creditnote-41ur.vercel.app/api/auth/callback"]

[pos]
embedded = true
