# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3e0a90c9ecdf9a085dfc7bd1c1c5fa6e"
name = "CreditNote"
application_url = "https://creditnote-41ur.vercel.app"
embedded = true
handle = "creditnote"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "customers/create",
  "customers/update",
  "orders/create",
  "orders/updated"
]
  uri = "/api/webhooks"

[access_scopes]
scopes = "read_customers,read_discounts,read_orders,write_customers,write_discounts,write_orders,read_products,read_inventory"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://creditnote-41ur.vercel.app/api/auth/callback",
  "https://creditnote-41ur.vercel.app/api/auth"
]

[pos]
embedded = true
