# QR Generator Extension - Create and print credit notes with QR codes
# API version 2025-07 with customer search and QR generation

api_version = "2025-07"

[[extensions]]
type = "ui_extension"
name = "qr-generator"
handle = "qr-generator"

# Tile on home screen
[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

# Modal dialog
[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"

[build]
command = ""
watch = []
