api_version = "2025-07"

[[extensions]]
type = "pos_ui_extension"
name = "Credit Note Scanner"
handle = "credit-note-scanner"

[[extensions.targeting]]
target = "pos.home.modal.render"

[[extensions.targeting]]
target = "pos.purchase.post.action.render"

[build]
command = "npm run build"
path = "dist"

[development]
entries = ["./src/index.ts"]
resource_url = "https://localhost:3000/extensions/credit-note-pos/assets/index.js"

[extension_settings]
[[extension_settings.fields]]
key = "enable_offline_mode"
type = "boolean"
name = "Enable offline mode"
description = "Allow credit operations when offline"
default = true

[[extension_settings.fields]]
key = "auto_apply_full_credit"
type = "boolean" 
name = "Auto-apply full credit"
description = "Automatically apply full credit amount when possible"
default = true

[[extension_settings.fields]]
key = "require_staff_confirmation"
type = "boolean"
name = "Require staff confirmation"
description = "Require staff confirmation before applying credits"
default = false

[[extension_settings.fields]]
key = "max_credit_amount"
type = "number"
name = "Maximum credit amount"
description = "Maximum credit amount that can be applied in a single transaction"
default = 1000