
api_version = "2025-07"

[[extensions]]
type = "ui_extension"
name = "Credit Creator"
uid = "b30de901-aa59-0600-5d76-a84f5a07f921758302d0"
handle = "credit-creator"
description = "Create credit notes - Issue new credit notes with QR code generation, print functionality, and database integration with enhanced error handling"

# module: file that contains your extension's source code
# target: location where your extension appears in POS
[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
