api_version = "2025-07"

[[extensions]]
uid = "93b3babe-c025-05dd-8173-006cc6798a0f9389f886"
type = "ui_extension"
name = "credit-note-creator"
handle = "credit-note-creator"
description = "Create credit notes with QR codes"

[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"

[build]
command = ""
watch = []
