api_version = "2025-07"

[[extensions]]
type = "ui_extension"
name = "test2"
uid = "6eabff02-c968-0cbc-bc7f-3b672928a761942ace2f"
handle = "test2"
description = "Credit Note Manager - View, search, and delete credit notes from database"

[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
