api_version = "2025-07"

[[extensions]]
type = "ui_extension"
name = "Credit Manager"
uid = "6eabff02-c968-0cbc-bc7f-3b672928a761942ace2f"
handle = "credit-manager"
description = "Manage credit notes - View, search, filter, and delete credit notes from PostgreSQL database with enhanced error handling"

[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
