# QR Scanner Extension - Scan and redeem credit notes via QR codes
# API version 2025-07 with CameraScanner component

api_version = "2025-07"

[[extensions]]
type = "ui_extension"
name = "qr-scanner"
handle = "qr-scanner"

# Tile on home screen
[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

# Modal dialog
[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"

[build]
command = ""
watch = []
