# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
uid = "2ea35025-c488-679f-7751-ab0dbf3c57530e8e9594"
type = "ui_extension"
name = "Credits Manager V3"
handle = "credit-manager-v3"
description = "Credit notes manager - V3.1.0 FINAL FIX - 2025-10-07 21:56 UTC - BUILD_121"

# Controls where in POS your extension will be injected,
# and the file that contains your extension’s source code.
[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
