# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
uid = "2ea35025-c488-679f-7751-ab0dbf3c57530e8e9594"
type = "ui_extension"
name = "Credits Manager V2"
handle = "credit-manager-v2"
description = "Credit notes - V2.0.0 - Final CDN bust 2025-10-06T19:45Z"

# Controls where in POS your extension will be injected,
# and the file that contains your extension’s source code.
[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
